openapi: 3.0.0
info:
  title: ТреУч
  description: API для мобильного приложения для тренеров и клиентов фитнес-залов
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
tags:
  - name: auth
    description: Аутентификация и авторизация
  - name: workouts
    description: Управление тренировками
  - name: muscle-groups
    description: Группы мышц
  - name: exercise-templates
    description: Шаблоны упражнений
  - name: reports
    description: Отчеты по тренировкам

paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя в системе
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '406':
          description: Некорректный формат данных
        '409':
          description: Пользователь с таким email уже существует
        '500':
          description: Внутренняя ошибка сервера

  /auth/login:
    post:
      tags:
        - auth
      summary: Вход в систему
      description: Аутентификация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Неверный email или пароль
        '404':
          description: Пользователь не найден
        '406':
          description: Некорректный формат данных
        '500':
          description: Внутренняя ошибка сервера

  /workouts:
    get:
      tags:
        - workouts
      summary: Получить список тренировок
      description: Возвращает список тренировок по параметрам
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer <token>
        - name: clientId
          in: query
          schema:
            type: integer
          description: ID клиента (опционально)
        - name: fromDate
          in: query
          schema:
            type: string
            format: date-time
          description: Начальная дата (YYYY-MM-DDTHH:MM:SS)
        - name: toDate
          in: query
          schema:
            type: string
            format: date-time
          description: Конечная дата (YYYY-MM-DDTHH:MM:SS)
      responses:
        '200':
          description: Успешное получение списка тренировок
          content:
            application/json:
              schema:
                type: object
                properties:
                  workouts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Workout'
        '403':
          description: Не авторизован
        '406':
          description: Недостаточно прав для этой информации
        '500':
          description: Внутренняя ошибка сервера

    post:
      tags:
        - workouts
      summary: Создать тренировку
      description: Создает новую тренировку
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer <token>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutCreateRequest'
      responses:
        '201':
          description: Тренировка создана
        '406':
          description: Некорректные данные
        '500':
          description: Внутренняя ошибка сервера

  /muscle-groups:
    get:
      tags:
        - muscle-groups
      summary: Получить группы мышц
      description: Возвращает список всех групп мышц или конкретную группу
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer <token>
        - name: muscleGroupsId
          in: query
          schema:
            type: integer
          description: ID группы мышц (опционально)
      responses:
        '200':
          description: Успешное получение списка групп мышц
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MuscleGroup'
                  - type: array
                    items:
                      $ref: '#/components/schemas/MuscleGroup'
        '401':
          description: Не авторизован
        '404':
          description: Группа мышц не найдена
        '500':
          description: Внутренняя ошибка сервера

  /exercise-templates:
    get:
      tags:
        - exercise-templates
      summary: Получить шаблоны упражнений
      description: Возвращает список шаблонов упражнений
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer <token>
      responses:
        '200':
          description: Успешное получение списка упражнений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExerciseTemplate'
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка сервера

  /reports/{workoutId}:
    post:
      tags:
        - reports
      summary: Создать отчет по тренировке
      description: Создает отчет о выполненной тренировке
      parameters:
        - name: workoutId
          in: path
          required: true
          schema:
            type: integer
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer <token>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutReportRequest'
      responses:
        '201':
          description: Отчет создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkoutReport'
        '406':
          description: Некорректные данные
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        lastName:
          type: string
          maxLength: 32
          description: Фамилия пользователя
        firstName:
          type: string
          maxLength: 32
          description: Имя пользователя
        patronymic:
          type: string
          maxLength: 32
          description: Отчество пользователя
        role:
          type: string
          enum: [CLIENT, TRAINER]
          description: Роль пользователя
        email:
          type: string
          maxLength: 64
          format: email
          description: Адрес электронной почты
        passwordHash:
          type: string
          maxLength: 256
          description: SHA-256 хеш пароля
      required:
        - lastName
        - firstName
        - role
        - email
        - passwordHash

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 64
          format: email
          description: Адрес электронной почты
        passwordHash:
          type: string
          maxLength: 256
          description: SHA-256 хеш пароля
      required:
        - email
        - passwordHash

    AuthResponse:
      type: object
      properties:
        userId:
          type: integer
          format: int64
          description: ID пользователя
        role:
          type: string
          enum: [TRAINER, CLIENT]
          description: Роль пользователя
        token:
          type: string
          description: JWT токен
        refreshToken:
          type: string
          description: Refresh токен

    Workout:
      type: object
      properties:
        name:
          type: string
          maxLength: 64
          description: Название тренировки
        trainerId:
          type: integer
          format: int64
          description: ID тренера
        clientId:
          type: integer
          format: int64
          description: ID клиента
        startDateTime:
          type: string
          format: date-time
          description: Дата и время начала (YYYY-MM-DDTHH:MM:SS)
        endDateTime:
          type: string
          format: date-time
          description: Дата и время окончания (YYYY-MM-DDTHH:MM:SS)
        status:
          type: string
          enum: [NOT_COMPILED, COMPILED, STARTED, FINISHED]
          description: Статус тренировки
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'

    WorkoutCreateRequest:
      type: object
      properties:
        auth_token:
          type: string
          maxLength: 4096
          description: JWT токен
        workout:
          $ref: '#/components/schemas/Workout'

    Exercise:
      type: object
      properties:
        number:
          type: integer
          description: Номер упражнения
        templateId:
          type: integer
          format: int64
          description: ID шаблона упражнения
        comment:
          type: string
          maxLength: 256
          description: Комментарий
        status:
          type: string
          enum: [NOT_STARTED, IN_PROGRESS, DONE, SKIPPED]
          description: Статус упражнения
        sets:
          type: array
          items:
            $ref: '#/components/schemas/Set'

    Set:
      type: object
      properties:
        setNumber:
          type: integer
          description: Номер подхода
        weight:
          type: number
          format: float
          description: Вес
        duration:
          type: integer
          description: Длительность (сек)
        restTime:
          type: integer
          description: Время отдыха (сек)

    MuscleGroup:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID группы мышц
        name:
          type: string
          maxLength: 50
          description: Название (заглавные_английские_буквы)
        displayName:
          type: string
          maxLength: 100
          description: Отображаемое название

    ExerciseTemplate:
      type: object
      properties:
        name:
          type: string
          maxLength: 64
          description: Название упражнения
        creatorId:
          type: integer
          format: int64
          description: ID создателя
        muscleGroups:
          type: array
          items:
            $ref: '#/components/schemas/MuscleGroup'
          description: Группы мышц
        description:
          type: string
          maxLength: 2048
          description: Описание
        media:
          type: array
          items:
            $ref: '#/components/schemas/ExerciseTemplateMedia'
          description: Медиафайлы

    ExerciseTemplateMedia:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID медиа
        fileUrl:
          type: string
          description: URL файла
        type:
          type: string
          enum: [IMAGE, VIDEO]
          description: Тип медиа

    WorkoutReportRequest:
      type: object
      properties:
        description:
          type: string
          description: Комментарии о выполненных упражнениях
        duration:
          type: integer
          description: Длительность тренировки в секундах

    WorkoutReport:
      type: object
      properties:
        workoutId:
          type: integer
          description: ID тренировки
        duration:
          type: integer
          description: Длительность тренировки в секундах
        description:
          type: string
          maxLength: 1024
          description: Комментарии о выполненных упражнениях